### PR TITLE
Add help; add "no bugs" text

### LINKED ISSUE #31: team page should have the tag on it somewhere
We use a specific tag to find bugs that edwin should show. We should have that tag show up on that team page.

Maybe a "help" section at the bottom or as a modal or something.

### PR DESCRIPTION
**Pull request by willkg**
- add the beginnings of a help section to the bottom of the timeline
  page that at least shows the team tag that you need to use to
  mark bugs
- in the case there are no bugs to show, show a "No bugs." message

Fixes #31 

r?

### CODE REVIEW

File: edwin/client/static/js/components/Timeline.js [hunk 1]
```diff
@@ -60,6 +60,7 @@ export default class TimelineApp extends ControllerComponent {
     let bugs = this.state.bugs.sortBy((bug) => -bug.get('state').value);
     let undoneBugs = bugs.filter((bug) => bug.get('state') !== BugStates.DONE);
     let doneBugs = bugs.filter((bug) => bug.get('state') === BugStates.DONE);
+    let teamTag = 'edwin-' + this.props.params.team;
```
Comment (mythmon) [inline edwin/client/static/js/components/Timeline.js:63]: This works, and we can leave it. However, generally for this kind of thing I've been using ES6 template strings. Using that syntax, this line would be 

```
let teamTag = `edwin-${this.props.params.team}`;
```
